<a href="https://colab.research.google.com/github/Asifleopard08/PIAIC_ASSIGNMENT-01/blob/main/PIAIC74044.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
#Import the numpy package under the name np
import numpy as np

In [2]:
#Create a null vector of size 10
null_vector = np.zeros(10)
null_vector

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [3]:
#Create a vector with values ranging from 10 to 49
a = np.arange(10, 50)
a

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [4]:
#Find the shape of previous array in question 3
np.shape(a)

(40,)

In [5]:
#Print the type of the previous array in question 3
a.dtype

dtype('int64')

In [6]:
#Print the numpy version and the configuration
np.__version__

'1.19.4'

In [7]:
np.show_config()

blas_mkl_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
openblas_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
blas_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
lapack_mkl_info:
  NOT AVAILABLE
openblas_lapack_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
lapack_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]


In [8]:
#Print the dimension of the array in question 3
a.ndim

1

In [9]:
#Create a boolean array with all the True values
A = np.array([4, 5, 6, 7, 8, 9])

A >= 4

array([ True,  True,  True,  True,  True,  True])

In [10]:
#Create a two dimensional array
B = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
B

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [11]:
#Create a three dimensional array
C = np.array([[[[1, 2, 3], [4, 5, 6], [7, 8, 9]]]])
C

array([[[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]]])

In [12]:
                                    ##Difficulty Level Easy
#Reverse a vector (first element becomes last)
D = np.arange(10)
D

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
D[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [14]:
#Create a null vector of size 10 but the fifth value which is 1
E = np.zeros(10)
E[4] = 1
E

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

In [15]:
#Create a 3x3 identity matrix
F = np.identity(3)
F

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [16]:
#Convert the data type of the given array from int to float
arr = np.array([1, 2, 3, 4, 5])
arr.astype('float')

array([1., 2., 3., 4., 5.])

In [17]:
#Multiply arr1 with arr2
arr1 = np.array([[1., 2., 3.], [4., 5., 6.]])
arr2 = np.array([[0., 4., 1.], [7., 2., 12.]])
arr3 = arr1 * arr2
arr3

array([[ 0.,  8.,  3.],
       [28., 10., 72.]])

In [18]:
#Make an array by comparing both the arrays provided above
arr1 = np.array([[1., 2., 3.], [4., 5., 6.]])
arr2 = np.array([[0., 4., 1.], [7., 2., 12.]])
comparison = arr1 == arr2
equal_arr = comparison.all()
equal_arr

False

In [19]:
#Extract all odd numbers from arr with values(0-9)
arr = np.arange(10)
Z = arr[arr % 2 == 1]
Z

array([1, 3, 5, 7, 9])

In [20]:
#Replace all odd numbers to -1 from previous array
Z[0:5] = -1
Z

array([-1, -1, -1, -1, -1])

In [21]:
#Replace the values of indexes 5,6,7 and 8 to 12
arr = np.arange(10)
arr[5:9]=12
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12, 12,  9])

In [22]:
#Create a 2d array with 1 on the border and 0 inside
X = np.ones((5,5))
X[1:-1,1:-1] = 0
X

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

In [23]:
                         ###Difficulty Level Medium
#Replace the value 5 to 12
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr2d[1][1] = 12
arr2d

array([[ 1,  2,  3],
       [ 4, 12,  6],
       [ 7,  8,  9]])

In [24]:
#Convert all the values of 1st array to 64
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
arr3d[0] = 64
arr3d

array([[[64, 64, 64],
        [64, 64, 64]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [25]:
#Make a 2-Dimensional array with values 0-9 and slice out the first 1st 1-D array from it
A = np.array([[0, 1, 2, 3, 4], [5, 6, 7, 8, 9]])
A[0][0]

0

In [26]:
#Make a 2-Dimensional array with values 0-9 and slice out the 2nd value from 2nd 1-D array from it
A[1][1]

6

In [27]:
#Make a 2-Dimensional array with values 0-9 and slice out the third column but only the first two rows
A[:, :4]

array([[0, 1, 2, 3],
       [5, 6, 7, 8]])

In [28]:
#Create a 10x10 array with random values and find the minimum and maximum values
Y = np.random.randn(10, 10)
Y

array([[-0.71468996,  1.33201222,  0.06899266, -0.02645704,  0.86083378,
        -0.0926509 ,  0.5980984 , -0.35252545,  0.06034467,  1.10003417],
       [-0.64597352, -0.6886558 ,  0.22781545, -2.20685936, -0.71531759,
        -1.03054308,  0.07645282, -0.57765823, -0.94230388,  0.28595621],
       [-0.0310084 , -1.96547624,  0.03674507,  0.20182207,  1.61797052,
         1.68769446, -1.99638605,  0.70404237, -0.49540304,  0.4330194 ],
       [-0.76245848, -0.39701591,  1.00541765, -0.11559239, -0.23853522,
         1.37783474,  0.23164896, -0.12058882, -1.35421944,  0.67771142],
       [-1.09532889, -0.97042722, -0.21302099,  0.54028926, -2.65965755,
        -0.84240955, -0.55304812,  0.15331189, -0.40136089, -0.3713538 ],
       [ 0.19413875,  0.06640882, -2.06963334, -0.81879491, -1.8051137 ,
         0.2891018 ,  0.57184866, -0.20173322,  0.56790837, -0.55198819],
       [ 0.04175723, -0.13974257,  1.02931209,  0.27569905, -1.20378972,
         0.27437914, -1.05486155,  0.94551229

In [29]:
Y.max()

1.6876944637605547

In [30]:
Y.min()

-2.659657551788217

In [31]:
#Find the common items between a and b
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
c = np.intersect1d(a, b)
c

array([2, 4])

In [32]:
#Find the positions where elements of a and b match
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
np.where(a==b)

(array([1, 3, 5, 7]),)

In [33]:
#Find all the values from array data where the values from array names are not equal to Will
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) 
data = np.random.randn(7, 4)
names != 'Will'

array([ True,  True, False,  True, False,  True,  True])

In [34]:
#Find all the values from array data where the values from array names are not equal to Will and Joe
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
data = np.random.randn(7, 4)
names != 'Will'

array([ True,  True, False,  True, False,  True,  True])

In [35]:
                           ###Difficulty Level Hard
#Create a 2D array of shape 5x3 to contain decimal numbers between 1 and 15.
Z = np.arange(1, 16).reshape(5, 3)
Z

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15]])

In [36]:
#Create an array of shape (2, 2, 4) with decimal numbers between 1 to 16.
Y = np.arange(1, 17).reshape(2, 2, 4)
Y

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8]],

       [[ 9, 10, 11, 12],
        [13, 14, 15, 16]]])

In [37]:
#Swap axes of the array you created in Question 32
Y.swapaxes(1, 2)

array([[[ 1,  5],
        [ 2,  6],
        [ 3,  7],
        [ 4,  8]],

       [[ 9, 13],
        [10, 14],
        [11, 15],
        [12, 16]]])

In [38]:
#Create an array of size 10, and find the square root of every element in the array, if the values less than 0.5, replace them with 0
Y = np.arange(10)
np.sqrt(Y)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [39]:
#Find the unique names and sort them out!
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
np.unique(names)

array(['Bob', 'Joe', 'Will'], dtype='<U4')

In [40]:
np.sort(names)

array(['Bob', 'Bob', 'Joe', 'Joe', 'Joe', 'Will', 'Will'], dtype='<U4')

In [41]:
#From array a remove all items present in array b
a = np.array([1,2,3,4,5]) 
b = np.array([5,6,7,8,9])
np.delete(a, 4)

array([1, 2, 3, 4])

In [42]:
#Following is the input NumPy array delete column two and insert following new column in its place
sampleArray = np.array([[34,43,73], [82,22,12], [53,94,66]])
newColumn = np.array([[10,10,10]])
sampleArray[:, 2:] = 10
sampleArray

array([[34, 43, 10],
       [82, 22, 10],
       [53, 94, 10]])

In [43]:
#Find the dot product of the above two matrix
x = np.array([[1., 2., 3.], [4., 5., 6.]])
y = np.array([[6., 23.], [-1, 7], [8, 9]])
z = np.dot(x, y)
z

array([[ 28.,  64.],
       [ 67., 181.]])

In [44]:
#Generate a matrix of 20 random values and find its cumulative sum
z = np.random.randn(4, 5)
z

array([[ 0.15278347, -1.89733318, -0.18826526,  0.69989419,  0.86259479],
       [-0.59999001,  0.81222718, -1.36964823,  0.42020413,  0.66999466],
       [ 0.35827541, -2.42260907,  0.55312635,  0.36411387,  0.54507862],
       [-0.80204342,  0.94461242, -1.05261536,  1.12500401,  0.32491091]])

In [45]:
z.cumsum()

array([ 0.15278347, -1.74454971, -1.93281497, -1.23292078, -0.37032599,
       -0.97031601, -0.15808883, -1.52773705, -1.10753292, -0.43753826,
       -0.07926284, -2.50187191, -1.94874556, -1.58463168, -1.03955306,
       -1.84159648, -0.89698406, -1.94959942, -0.82459541, -0.49968449])